In [2]:
import pandas as pd
import numpy as np

# Set the maximum number of rows displayed to 10
pd.set_option('display.max_rows', 10)

# Set the maximum number of columns displayed to 10
pd.set_option('display.max_columns', 10)

# Create a large DataFrame for demonstration
df = pd.DataFrame(np.random.rand(100, 50))

# Display the DataFrame
df

,0,1,2,3,4,...,45,46,47,48,49
0,0.084401,0.144020,0.630168,0.082893,0.010646,...,0.439315,0.960079,0.477193,0.483943,0.183817
1,0.102967,0.431081,0.114751,0.179645,0.617208,...,0.050888,0.757028,0.483107,0.463348,0.351411
2,0.833055,0.065347,0.969728,0.768612,0.615392,...,0.798466,0.434170,0.831012,0.994230,0.558402
3,0.879687,0.004589,0.851243,0.286956,0.346935,...,0.103516,0.770485,0.996849,0.639537,0.856120
4,0.957510,0.638053,0.267419,0.250669,0.739796,...,0.044278,0.731527,0.909102,0.513736,0.791169
...,...,...,...,...,...,...,...,...,...,...,...
95,0.684340,0.213107,0.525123,0.379839,0.304796,...,0.666990,0.204707,0.240117,0.848214,0.629659
96,0.393814,0.051475,0.809528,0.164640,0.392835,...,0.280053,0.573599,0.012597,0.312843,0.659750
97,0.214191,0.898663,0.817606,0.703387,0.213346,...,0.441001,0.209060,0.975589,0.049224,0.663008
98,0.495068,0.456223,0.610522,0.348654,0.359317,...,0.197463,0.900321,0.653388,0.377229,0.506846
99,0.623702,0.412365,0.131045,0.852665,0.632728,...,0.993547,0.429191,0.578218,0.577627,0.674276

In [5]:
import pandas as pd
from ipydatagrid import DataGrid
from sklearn.datasets import load_iris

# Create a simple dataframe
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)

# Display the dataframe with ipydatagrid
datagrid = DataGrid(df)
datagrid

DataGrid(auto_fit_params={'area': 'all', 'padding': 30, 'numCols': None}, corner_renderer=None, default_render…